[package]
name = "rust-template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = ""
homepage = "https://github.com/ryo33/rust-template"
repository = "https://github.com/ryo33/rust-template"
readme = "README.md"
keywords = []
categories = []

[dependencies]
